/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated.painel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClassesClassIdIndexRouteImport } from './routes/_authenticated.classes.$classId.index'
import { Route as AuthenticatedClassesClassIdLecturesLectureIdRouteImport } from './routes/_authenticated.classes.$classId.lectures.$lectureId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesClassIdIndexRoute =
  AuthenticatedClassesClassIdIndexRouteImport.update({
    id: '/classes/$classId/',
    path: '/classes/$classId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesClassIdLecturesLectureIdRoute =
  AuthenticatedClassesClassIdLecturesLectureIdRouteImport.update({
    id: '/classes/$classId/lectures/$lectureId',
    path: '/classes/$classId/lectures/$lectureId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/classes/$classId/': typeof AuthenticatedClassesClassIdIndexRoute
  '/classes/$classId/lectures/$lectureId': typeof AuthenticatedClassesClassIdLecturesLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdIndexRoute
  '/classes/$classId/lectures/$lectureId': typeof AuthenticatedClassesClassIdLecturesLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/classes/$classId/': typeof AuthenticatedClassesClassIdIndexRoute
  '/_authenticated/classes/$classId/lectures/$lectureId': typeof AuthenticatedClassesClassIdLecturesLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/painel'
    | '/classes/$classId/'
    | '/classes/$classId/lectures/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/painel'
    | '/classes/$classId'
    | '/classes/$classId/lectures/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/painel'
    | '/_authenticated/classes/$classId/'
    | '/_authenticated/classes/$classId/lectures/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId/': {
      id: '/_authenticated/classes/$classId/'
      path: '/classes/$classId'
      fullPath: '/classes/$classId/'
      preLoaderRoute: typeof AuthenticatedClassesClassIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/$classId/lectures/$lectureId': {
      id: '/_authenticated/classes/$classId/lectures/$lectureId'
      path: '/classes/$classId/lectures/$lectureId'
      fullPath: '/classes/$classId/lectures/$lectureId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdLecturesLectureIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedClassesClassIdIndexRoute: typeof AuthenticatedClassesClassIdIndexRoute
  AuthenticatedClassesClassIdLecturesLectureIdRoute: typeof AuthenticatedClassesClassIdLecturesLectureIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedClassesClassIdIndexRoute: AuthenticatedClassesClassIdIndexRoute,
  AuthenticatedClassesClassIdLecturesLectureIdRoute:
    AuthenticatedClassesClassIdLecturesLectureIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
